config/routes.rb
Chagua::Application.routes.draw do
 resources :options

  resources :polls do 
  resources :options

end
  get "sessions/new"
  get "welcome/index"
  get "welcome/about"
  get "log_out" => "sessions#destroy", :as => "log_out"
  post "notify_users" =>"polls#notify_users", :as =>"notify_users"
  resources :voters, :sessions, :votes
 
  match "/voters/:id/approve "=> "voters#approve",:as =>"voter_approve",via: [:post]

  root 'welcome#index'

  

end

app/models/option.rb
class Option < ActiveRecord::Base
	belongs_to :poll
	validates :name, presence:true
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :set_option, only: [:show, :edit, :update, :destroy]

  # GET /options
  # GET /options.json
  def index
    @options = Option.all
  end

  # GET /options/1
  # GET /options/1.json
  def show
  end

  # GET /options/new
  def new
    @option = Option.new
  end

  # GET /options/1/edit
  def edit
  end

  # POST /options
  # POST /options.json
  def create
    @poll = Poll.find(params[ :poll_id])
    @option = @poll.options.create(option_params)
    redirect_to poll_path(@poll)
  end
  
  # PATCH/PUT /options/1
  # PATCH/PUT /options/1.json
  def update
    respond_to do |format|
      if @option.update(option_params)
        format.html { redirect_to @option, notice: 'Option was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option.destroy
    respond_to do |format|
      format.html { redirect_to options_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option
      @option = Option.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def option_params
      params.require(:option).permit(:name, :poll)
    end
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/views/options/_form.html.erb
<%= form_for(@option) do |f| %>
  <% if @option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@option.errors.count, "error") %> prohibited this option from being saved:</h2>

      <ul>
      <% @option.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :poll %><br>
    <%= f.text_field :poll %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/options/edit.html.erb
<h1>Editing option</h1>

<%= render 'form' %>

<%= link_to 'Show', @option %> |
<%= link_to 'Back', options_path %>

app/views/options/index.html.erb
<h1>Listing options</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Poll</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @options.each do |option| %>
      <tr>
        <td><%= option.name %></td>
        <td><%= option.poll %></td>
        <td><%= link_to 'Show', option %></td>
        <td><%= link_to 'Edit', edit_option_path(option) %></td>
        <td><%= link_to 'Destroy', option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Option', new_option_path %>

app/views/options/new.html.erb
<h1>New option</h1>

<%= render 'form' %>

<%= link_to 'Back', options_path %>

app/views/options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @option.name %>
</p>

<p>
  <strong>Poll:</strong>
  <%= @option.poll %>
</p>

<%= link_to 'Edit', edit_option_path(@option) %> |
<%= link_to 'Back', options_path %>