config/routes.rb
Chagua::Application.routes.draw do
 resources :options

  resources :polls do 
  resources :options

end
  get "sessions/new"
  get "welcome/index"
  get "welcome/about"
  get "log_out" => "sessions#destroy", :as => "log_out"
  post "notify_users" =>"polls#notify_users", :as =>"notify_users"
  resources :voters, :sessions, :votes
 
  match "/voters/:id/approve "=> "voters#approve",:as =>"voter_approve",via: [:post]

  root 'welcome#index'

  

end

app/models/voter.rb
class Voter < ActiveRecord::Base

	validates :email, presence:true, uniqueness:true, email:true
	validates :username, presence:true, uniqueness:{case_sensitive:false}
	validates :password, presence:true, length:{in: 6..10}
	validates :phone, presence:true
	def self.authenticate(username, password)
        #only approved voters should be able to log in
        voter = find_by_username_and_password_and_approved(username, password, true)    
    end
end

app/controllers/voters_controller.rb
class VotersController < ApplicationController
  before_action :authorise_admin, only:[:index, :show]
  before_action :set_voter, only: [:show, :edit, :update, :destroy]

  # GET /voters
  # GET /voters.json
  def index
    if  !view_context.admin_is_logged_in?
      redirect_to new_session_path
    else
      @voters = Voter.all.order("approved")

      end
  end

  # GET /voters/1
  # GET /voters/1.json
  def show
  end

  # GET /voters/new
  def new
    @voter = Voter.new
  end

  # GET /voters/1/edit
  def edit
  end

  # POST /voters
  # POST /voters.json
  def create
    @voter = Voter.new(voter_params)

    respond_to do |format|
      if @voter.save
        format.html { redirect_to root_path, notice: "Thanks  for registering.#{@voter.username}We will get back after aprroval"}
        format.json { render action: 'show', status: :created, location: @voter }
      else
        format.html { render action: 'new' }
        format.json { render json: @voter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voters/1
  # PATCH/PUT /voters/1.json
  def update
    respond_to do |format|
      if @voter.update(voter_params)
        format.html { redirect_to @voter, notice: 'Voter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @voter.errors, status: :unprocessable_entity }
      end

    end
  end

  def approve
     @voter = Voter.find(params[:id])
     @voter.approved = true
     @voter.save!
     VoterMailer.approval_email(@voter).deliver
    redirect_to voters_path, notice:'Voter was successfully approved'
  end

  # DELETE /voters/1
  # DELETE /voters/1.json
  def destroy
    @voter.destroy
    respond_to do |format|
      format.html { redirect_to voters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voter
      @voter = Voter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voter_params
      params.require(:voter).permit(:email, :username, :password, :phone, :approved)
    end
end

app/helpers/voters_helper.rb
module VotersHelper
end

app/views/voters/_form.html.erb
<%= form_for(@voter) do |f| %>
  <% if @voter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voter.errors.count, "error") %> prohibited this voter from being saved:</h2>

      <ul>
      <% @voter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
   <div class="field">
   <% if admin_is_logged_in? %>

    <%= f.label :approved %><br>
    <%= f.check_box :approved %>
    <%else%>
    <% end %>

  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/voters/edit.html.erb
<h1>Editing voter</h1>

<%= render 'form' %>

<%= link_to 'Show', @voter %> |
<%= link_to 'Back', voters_path %>

app/views/voters/index.html.erb
<h1>Listing voters</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Username</th>
      
      <th>Phone</th>
      <th>Approved</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  

    <% @voters.each do |voter| %>
    
     <tr> 

       <td><%= voter.email %></td>
        <td><%= voter.username %></td>        
        <td><%= voter.phone %></td>
        <td><%= voter.approved %></td>
        <td><%= link_to 'Show', voter %></td>
        <td><%= link_to 'Edit', edit_voter_path(voter) %></td>
        <td><%= link_to 'Destroy', voter, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        <%if !voter.approved %>
       <td><%= link_to 'approve', voter_approve_path(voter), method: :post, data: { confirm: 'Are you sure?'} %></td><% end %>
      </tr>
    
    
    <%end%>  
  </tbody>
</table>

app/views/voters/new.html.erb
<h1>New voter</h1>


<%= render 'form' %>

<%= link_to 'Back', voters_path %>

app/views/voters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @voter.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @voter.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @voter.password %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @voter.phone %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @voter.approved%>
</p>

<%= link_to 'Edit', edit_voter_path(@voter) %> |
<%= link_to 'Back', voters_path %>