config/routes.rb
Chagua::Application.routes.draw do
 resources :options

  resources :polls do 
  resources :options

end
  get "sessions/new"
  get "welcome/index"
  get "welcome/about"
  get "log_out" => "sessions#destroy", :as => "log_out"
  post "notify_users" =>"polls#notify_users", :as =>"notify_users"
  resources :voters, :sessions, :votes
 
  match "/voters/:id/approve "=> "voters#approve",:as =>"voter_approve",via: [:post]

  root 'welcome#index'

  

end

app/models/poll.rb
class Poll < ActiveRecord::Base
  belongs_to :admin
  has_many :options
  validates :question, presence: true

  validates :deadline, date: {after: :start_date, message: "Deadline must be after start date"}
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
before_action :set_poll, only: [:show, :edit, :update, :destroy]
before_action :authorise_admin, only: [:new, :create, :edit, :destroy]
  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)
    @poll.admin_id = session[:user].id
 
    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render action: 'show', status: :created, location: @poll }
      else
        format.html { render action: 'new' }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end
def notify_users
 Voter.where('approved = ?', true).each do |voter|
    VoterMailer.new_poll_email(voter.email).deliver
    end

    redirect_to polls_path,notice:"Poll was successfully emailed"
  
end
  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:question, :start_date, :deadline, :admin_id)
    end
end

app/helpers/polls_helper.rb
module PollsHelper
	 def user_is_logged_in?
        # This could be either a voter or admin
        voter_is_logged_in? || admin_is_logged_in?
    end
    
   def admin_is_logged_in?
        session[:user] != nil && session[:user].is_a?(Admin)
    end

    def voter_is_logged_in?
        session[:user] != nil && session[:user].is_a?(Voter)
    end

end

app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/polls/edit.html.erb
<h1>Editing poll</h1>
<% if admin_is_logged_in? %>

<%= render 'form' %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

 <% end %>

app/views/polls/index.html.erb
<h1>Listing polls</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Start date</th>
      <th>Deadline</th>
      <th>Admin</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= poll.question %></td>
        <td><%= poll.start_date %></td>
        <td><%= poll.deadline.to_s(:simple) %></td>
        <td><%= poll.admin %></td>
        <td><%= link_to 'Show', poll %></td>
       <% if admin_is_logged_in? %>

        <td><%= link_to 'Edit', edit_poll_path(poll) %></td>
        <td><%= link_to 'Destroy', poll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poll', new_poll_path %>

app/views/polls/new.html.erb
<h1>New poll</h1>

<%= render 'form' %>

<%= link_to 'Back', polls_path %>

app/views/polls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @poll.question %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @poll.start_date %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @poll.deadline %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @poll.admin.username %>
</p>

<%= link_to 'Edit', edit_poll_path(@poll) %> |
<%= link_to 'Back', polls_path %>
<% @poll.options.each do |option| %>
  <li><%= option.name %></li>
  <%end%>
  
<h2>Options</h2>
<ul>
	
</ul>
<%=form_for ([@poll, @poll.options.build]) do |f| %>
<%=f.label :name %>
<%=f.text_field :name %>
<%=f.submit %>
<% end %>

<%= button_to "notify voters", notify_users_path %>